// File lang/cpp/src/messages/TIM.hpp
// Auto-generated by pyUBX generateCPP.py v0.2 on 2023-06-06T19:57:04.624219
// See https://github.com/mayeranalytics/pyUBX
// DO NOT MODIFY THIS FILE!

#ifndef __TIM_H__
#define __TIM_H__
#include "Ubx.hpp"

/* Message class TIM.
 */
namespace ubx
{
namespace TIM {

constexpr uint8_t classID = 13;

struct __attribute__((packed)) SVIN : public SerializeCommon
{
    virtual uint8_t getClassId(void) const override;
    virtual uint8_t getMessageId(void) const override;
    virtual const std::string &getClassName(void) const override;
    virtual std::string getMessageName(void) const override;
    virtual std::string getDescription(void) const override;
    virtual uint8_t* getDataStartAddress(void) const override;
    virtual uint16_t getDataSize(void) const override;

    static constexpr uint8_t messageID = 4;

    struct __attribute__((packed)) _data {
        uint32_t dur;
        int32_t meanX;
        int32_t meanY;
        int32_t meanZ;
        uint32_t meanV;
        uint32_t obs;
        uint8_t valid;
        uint8_t active;
        uint16_t reserved;

    } data;
};

} // namespace TIM
} // namespace ubx
#endif // ifndef __TIM_H__
