// File lang/cpp/src/parseUbxMessage.hpp
// Auto-generated by pyUBX generateCPP.py v0.2 on 2023-06-07T13:38:14.201354
// See https://github.com/mayeranalytics/pyUBX
// DO NOT MODIFY THIS FILE!

#ifndef __PARSE_UBX_MESSAGE_H__
#define __PARSE_UBX_MESSAGE_H__

#include "parseUbxMessageBase.hpp"
#include "messages/ACK.hpp"
#include "messages/CFG.hpp"
#include "messages/ESF.hpp"
#include "messages/LOG.hpp"
#include "messages/MGA.hpp"
#include "messages/MON.hpp"
#include "messages/NAV.hpp"
#include "messages/RXM.hpp"
#include "messages/TEST.hpp"
#include "messages/TIM.hpp"

namespace ubx
{
    /**
     * @brief Class which is determined to parse byte array and return UBX object.
     */
    class ParseUbxMessage : public ParseUbxMessageBase
    {
        public:
            ParseUbxMessage():ParseUbxMessageBase(){};
        protected:
            /**
             * @brief Return Ubx object parsed from given buffer and object details.
             *
             * @param buf buffer with data
             * @param len buffer length
             * @param classId Ubx class id
             * @param messageID Ubx message id
             * @param isGet Is get type.
             *
             * @return std::shared_ptr<SerializeCommon> Nullptr or shared_ptr of UBX object.
             */
            virtual std::shared_ptr<SerializeCommon> createUbx(const uint8_t *buf, uint16_t len, uint8_t classId, uint8_t messageID, bool isGet = true) const override;
    };
}
#endif // #define __PARSE_UBX_MESSAGE_H__
