// File lang/cpp/src/parseUbxMessage.hpp
// Auto-generated by pyUBX generateCPP.py v0.1 on 2023-04-08T18:03:13.560181
// See https://github.com/mayeranalytics/pyUBX
// DO NOT MODIFY THIS FILE!

#ifndef __PARSE_UBX_MESSAGE_H__
#define __PARSE_UBX_MESSAGE_H__

#include "parseUbxMessageBase.hpp"
#include "messages/ACK.hpp"
#include "messages/CFG.hpp"
#include "messages/ESF.hpp"
#include "messages/LOG.hpp"
#include "messages/MGA.hpp"
#include "messages/MON.hpp"
#include "messages/NAV.hpp"
#include "messages/TEST.hpp"
#include "messages/TIM.hpp"

namespace ubx
{
    class ParseUbxMessage : public ParseUbxMessageBase
    {
        public:
            ParseUbxMessage():ParseUbxMessageBase(){};
        protected:
            virtual std::shared_ptr<SerializeCommon> createUbx(const uint8_t *buf, uint16_t len, uint8_t classId, uint8_t messageID, bool isGet = true) const override;
    };
}
#endif // #define __PARSE_UBX_MESSAGE_H__
